version: '3.8'

services:
  spark-iceberg:
    image: tabulario/spark-iceberg:3.5.5_1.8.1
    container_name: spark-iceberg
    ports:
      - "8888:8888"  # Jupyter Notebook
      - "8080:8080"  # Spark UI
      - "10000:10000"
      - "10001:10001"
    networks:
      iceberg_net:
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
      AWS_REGION: us-east-1
    depends_on:
      - minio
      - iceberg-rest
    volumes:
      - ./warehouse:/home/iceberg/warehouse
      - ./notebooks/:/home/iceberg/notebooks/
      - ./infra/spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
  iceberg-rest:
    image: apache/iceberg-rest-fixture
    container_name: iceberg-rest
    networks:
      iceberg_net:
    ports:
      - 8181:8181
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    networks:
      iceberg_net:
        aliases:
          - warehouse.minio
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - minio_data:/data
  # Development Flink container with PyFlink and Jupyter
  flink-dev:
    build:
      context: ./infra/flink
      dockerfile: Dockerfile
    container_name: flink-dev
    ports:
      - "8082:8081"   # Flink Web UI (keeping original port mapping)
      - "8889:8888"   # Jupyter Lab (avoiding conflict with Spark)
      - "6123:6123"   # JobManager RPC
      - "6124:6124"   # Blob server
    networks:
      - iceberg_net
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - FLINK_PROPERTIES=jobmanager.rpc.address:flink-dev
    volumes:
      - ./infra/flink/notebooks:/opt/workspace/notebooks
      - ./infra/flink/examples:/opt/workspace/examples
      - .:/opt/workspace/project  # Mount project root for development
      - flink-dev-data:/opt/workspace/data
    depends_on:
      - minio
      - iceberg-rest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/overview"]
      interval: 30s
      timeout: 10s
      retries: 3

  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    networks:
      iceberg_net:
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc anonymous set public minio/warehouse;
      tail -f /dev/null
      "

volumes:
  minio_data:
  iceberg_data:
  jupyter_data:
  flink-dev-data:

networks:
  iceberg_net: